name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3-pytest python3-gi \
            gir1.2-gtk-4.0 gir1.2-adw-1

      - name: Test
        run: pytest-3 -v tests/
